/* glossary.js - Vietnamese -> English dictionary for Sinh hoc + Vat ly 8.
   Each entry: [vi, en, type?]. type "common" = soft underline.
   Order matters: longer phrases first. Used only when current lang === "vi". */
window.GLOSSARY = [
/* ===== BIOLOGY: skeletal & muscular ===== */
["bộ xương","skeleton"],
["xương dài","long bone"],
["xương ngắn","short bone"],
["xương dẹt","flat bone"],
["xương","bone"],
["khớp động","movable / synovial joint"],
["khớp bán động","semi-movable joint"],
["khớp bất động","immovable joint"],
["khớp","joint"],
["cốt giao","collagen"],
["muối khoáng","mineral salts"],
["cơ vân","skeletal (striated) muscle"],
["cơ trơn","smooth muscle"],
["cơ tim","cardiac muscle"],
["sợi cơ","muscle fiber"],
["tơ cơ","myofilament"],
["dây chằng","ligament"],
["gân","tendon"],
["sụn","cartilage"],
["cong vẹo cột sống","spinal curvature"],
["cột sống","spine"],
/* ===== BIOLOGY: digestive ===== */
["hệ tiêu hóa","digestive system"],
["ống tiêu hóa","digestive tract"],
["dạ dày","stomach"],
["ruột non","small intestine"],
["ruột già","large intestine"],
["thực quản","esophagus"],
["miệng","mouth"],
["khoang miệng","oral cavity"],
["tuyến nước bọt","salivary gland"],
["nước bọt","saliva"],
["gan","liver"],
["mật","bile"],
["dịch mật","bile juice"],
["dịch vị","gastric juice"],
["dịch tụy","pancreatic juice"],
["enzyme","enzyme"],
["amylase","amylase"],
["pepsin","pepsin"],
["lipase","lipase"],
["protein","protein"],
["lipid","lipid"],
["chất béo","fat / lipid"],
["tinh bột","starch"],
["đường","sugar"],
["maltose","maltose"],
["vitamin","vitamin"],
["khoáng chất","minerals"],
["hấp thụ","absorb / absorption"],
["lông ruột","intestinal villi"],
["vi nhung mao","microvilli"],
["còi xương","rickets"],
["bướu cổ","goiter"],
["quáng gà","night blindness"],
/* ===== BIOLOGY: circulatory ===== */
["hệ tuần hoàn","circulatory system"],
["vòng tuần hoàn nhỏ","pulmonary (lesser) circulation"],
["vòng tuần hoàn lớn","systemic (greater) circulation"],
["vòng tuần hoàn","circulation"],
["tim","heart"],
["tâm thất phải","right ventricle"],
["tâm thất trái","left ventricle"],
["tâm nhĩ phải","right atrium"],
["tâm nhĩ trái","left atrium"],
["tâm thất","ventricle"],
["tâm nhĩ","atrium"],
["động mạch","artery"],
["tĩnh mạch","vein"],
["mao mạch","capillary"],
["mạch máu","blood vessel"],
["máu","blood"],
["hồng cầu","red blood cell"],
["bạch cầu","white blood cell"],
["tiểu cầu","platelet"],
["huyết tương","plasma"],
["huyết áp","blood pressure"],
["nhóm máu","blood group"],
["kháng nguyên","antigen"],
["kháng thể","antibody"],
["hemoglobin","hemoglobin"],
["đông máu","blood clotting"],
["fibrin","fibrin"],
/* ===== BIOLOGY: respiratory ===== */
["hệ hô hấp","respiratory system"],
["phổi","lungs"],
["phế nang","alveolus"],
["khí quản","trachea"],
["phế quản","bronchus"],
["mũi","nose"],
["thanh quản","larynx"],
["cơ hoành","diaphragm"],
["cơ liên sườn","intercostal muscle"],
["lồng ngực","thoracic cavity"],
["hít vào","inhale / inhalation"],
["thở ra","exhale / exhalation"],
["hô hấp","respiration"],
["trao đổi khí","gas exchange"],
["hen suyễn","asthma"],
["lao phổi","tuberculosis"],
["viêm phổi","pneumonia"],
["viêm gan","hepatitis"],
["khói thuốc","tobacco smoke"],
["ung thư phổi","lung cancer"],
/* ===== BIOLOGY: excretory & skin ===== */
["hệ bài tiết","excretory system"],
["thận","kidneys"],
["ống dẫn nước tiểu","ureter"],
["bàng quang","urinary bladder"],
["ống đái","urethra"],
["nephron","nephron"],
["nước tiểu","urine"],
["lọc máu","blood filtration"],
["da","skin"],
["biểu bì","epidermis"],
["lớp bì","dermis"],
["lớp mỡ dưới da","subcutaneous fat"],
["mồ hôi","sweat"],
["tuyến mồ hôi","sweat gland"],
["tuyến nhờn","sebaceous gland"],
["xúc giác","sense of touch"],
/* ===== BIOLOGY: nervous & senses ===== */
["hệ thần kinh","nervous system"],
["não","brain"],
["bộ não","brain"],
["đại não","cerebrum"],
["tiểu não","cerebellum"],
["hành não","medulla oblongata"],
["trung não","midbrain"],
["tủy sống","spinal cord"],
["dây thần kinh","nerve"],
["nơron","neuron"],
["sợi nhánh","dendrite"],
["sợi trục","axon"],
["synapse","synapse"],
["xung thần kinh","nerve impulse"],
["phản xạ","reflex"],
["cung phản xạ","reflex arc"],
["mắt","eye"],
["võng mạc","retina"],
["giác mạc","cornea"],
["thủy tinh thể","lens (eye)"],
["đồng tử","pupil"],
["mống mắt","iris"],
["cận thị","myopia / nearsightedness"],
["viễn thị","hyperopia / farsightedness"],
["loạn thị","astigmatism"],
["kính phân kỳ","concave / diverging lens"],
["kính hội tụ","convex / converging lens"],
["tai","ear"],
["tiền đình","vestibular apparatus"],
["thăng bằng","balance"],
["thị giác","sight / vision"],
["thính giác","hearing"],
["vị giác","taste"],
["khứu giác","smell"],
/* ===== BIOLOGY: endocrine & reproduction ===== */
["hệ nội tiết","endocrine system"],
["hormone","hormone"],
["tuyến nội tiết","endocrine gland"],
["tuyến ngoại tiết","exocrine gland"],
["tuyến giáp","thyroid"],
["tuyến yên","pituitary gland"],
["tuyến tụy","pancreas"],
["tuyến thượng thận","adrenal gland"],
["đảo tụy","pancreatic islets"],
["insulin","insulin"],
["thyroxine","thyroxine"],
["adrenaline","adrenaline"],
["estrogen","estrogen"],
["progesterone","progesterone"],
["testosterone","testosterone"],
["đái tháo đường","diabetes mellitus"],
["tiểu đường","diabetes"],
["iod","iodine"],
["hệ sinh sản","reproductive system"],
["sinh sản","reproduction"],
["tinh hoàn","testis"],
["mào tinh","epididymis"],
["ống dẫn tinh","vas deferens"],
["buồng trứng","ovary"],
["ống dẫn trứng","fallopian tube"],
["tử cung","uterus"],
["âm đạo","vagina"],
["tinh trùng","sperm"],
["trứng","egg / ovum"],
["thụ tinh","fertilization"],
["thai","fetus / pregnancy"],
["tránh thai","contraception"],
["vị thành niên","adolescent"],
["HIV","HIV"],
["AIDS","AIDS"],
["bệnh tả","cholera"],
["quai bị","mumps"],
["sởi","measles"],
/* ===== BIOLOGY: ecology ===== */
["môi trường","environment"],
["sinh vật","organism"],
["quần thể","population"],
["quần xã","community"],
["hệ sinh thái","ecosystem"],
["sinh cảnh","habitat"],
["nhân tố vô sinh","abiotic factor"],
["nhân tố hữu sinh","biotic factor"],
["chuỗi thức ăn","food chain"],
["lưới thức ăn","food web"],
["sinh vật sản xuất","producer"],
["sinh vật tiêu thụ","consumer"],
["sinh vật tiêu thụ bậc 1","primary consumer"],
["sinh vật tiêu thụ bậc 2","secondary consumer"],
["sinh vật phân giải","decomposer"],
["đa dạng sinh học","biodiversity"],
["khu bảo tồn","conservation area / reserve"],
["hiệu ứng nhà kính","greenhouse effect"],
["biến đổi khí hậu","climate change"],
["ô nhiễm môi trường","environmental pollution"],
["ô nhiễm","pollution"],
["khí nhà kính","greenhouse gas"],
["vi khuẩn","bacteria"],
["nấm","fungi"],
["động vật ăn cỏ","herbivore"],
["động vật ăn thịt","carnivore"],
["côn trùng","insect"],
["cây xanh","green plant"],
["thực vật","plants"],
["động vật","animals"],
/* ===== PHYSICS: electricity ===== */
["điện tích","electric charge"],
["điện tích dương","positive charge"],
["điện tích âm","negative charge"],
["dòng điện","electric current"],
["hiệu điện thế","voltage"],
["cường độ dòng điện","current intensity"],
["mạch điện","circuit"],
["mạch điện kín","closed circuit"],
["mạch điện hở","open circuit"],
["mạch nối tiếp","series circuit"],
["mạch song song","parallel circuit"],
["mạch hở","open circuit"],
["mạch kín","closed circuit"],
["chập mạch","short circuit"],
["vật dẫn điện","conductor"],
["vật cách điện","insulator"],
["dây dẫn","conducting wire"],
["dây trần","bare wire"],
["electron","electron"],
["electron tự do","free electron"],
["proton","proton"],
["neutron","neutron"],
["nguyên tử trung hòa","neutral atom"],
["pin","battery / cell"],
["nguồn điện","power source"],
["cực dương","positive terminal"],
["cực âm","negative terminal"],
["bóng đèn","light bulb"],
["đèn dây tóc","filament lamp"],
["đèn LED","LED lamp"],
["đèn huỳnh quang","fluorescent lamp"],
["đèn neon","neon lamp"],
["công tắc","switch"],
["cầu chì","fuse"],
["aptomat","circuit breaker"],
["cầu dao","main switch"],
["vôn kế","voltmeter"],
["ampe kế","ammeter"],
["vôn","volt (V)"],
["ampe","ampere (A)"],
["nhiễm điện","electrically charged"],
["cọ xát","friction (rubbing)"],
["nhiễm điện do cọ xát","charging by friction"],
["bóng bay","balloon"],
["thước nhựa","plastic ruler"],
["len","wool"],
/* ===== PHYSICS: effects of current ===== */
["tác dụng nhiệt","heating effect"],
["tác dụng phát sáng","light-emitting effect"],
["tác dụng từ","magnetic effect"],
["tác dụng hóa học","chemical effect"],
["tác dụng sinh lý","physiological effect"],
["nam châm điện","electromagnet"],
["nam châm","magnet"],
["động cơ điện","electric motor"],
["chuông điện","electric bell"],
["bàn là","electric iron"],
["bàn ủi điện","electric iron"],
["bếp điện","electric stove"],
["ấm điện","electric kettle"],
["bếp từ","induction stove"],
["mạ điện","electroplating"],
["mạ đồng","copper plating"],
["mạ vàng","gold plating"],
["điện giật","electric shock"],
["máy kích tim","defibrillator"],
/* ===== PHYSICS: heat ===== */
["nhiệt độ","temperature"],
["nhiệt năng","thermal energy"],
["năng lượng nhiệt","thermal energy"],
["dẫn nhiệt","conduction"],
["đối lưu","convection"],
["bức xạ nhiệt","thermal radiation"],
["bức xạ","radiation"],
["chân không","vacuum"],
["sóng điện từ","electromagnetic wave"],
["hồng ngoại","infrared"],
["truyền nhiệt","heat transfer"],
["cân bằng nhiệt","thermal equilibrium"],
["dẫn nhiệt tốt","good thermal conductor"],
["cách nhiệt","insulating (thermal)"],
["bình thủy","vacuum flask"],
["phích nước","thermos / vacuum flask"],
["áo bông","padded jacket"],
["chăn lông","wool blanket"],
["nồi","pot"],
["cán nồi","pot handle"],
["nhôm","aluminum"],
["sắt","iron"],
["đồng","copper"],
["bạc","silver"],
["sứ","porcelain"],
["thủy tinh","glass"],
["cao su","rubber"],
["gỗ","wood"],
["khối lượng riêng","density"],
["nhiệt độ cháy","ignition temperature"],
/* ===== Common Vietnamese (soft underline) ===== */
["nguyên tắc","principle","common"],
["loại","type / kind","common"],
["số lượng","quantity","common"],
["số","number","common"],
["tổng","total","common"],
["phần","part","common"],
["cách","way / manner","common"],
["ví dụ","example","common"],
["màu sắc","color","common"],
["màu đỏ","red","common"],
["màu xanh","blue / green","common"],
["màu hồng","pink","common"],
["màu vàng","yellow","common"],
["màu trắng","white","common"],
["màu đen","black","common"],
["màu","color","common"],
["mùi","smell / odor","common"],
["thường","usually","common"],
["định nghĩa","definition","common"],
["khái niệm","concept","common"],
["phát biểu","statement","common"],
["dụng cụ","apparatus / tool","common"],
["nhà","house","common"],
["nguồn","source","common"],
["cung cấp","supply / provide","common"],
["sử dụng","use","common"],
["dùng","use","common"],
["thêm","add","common"],
["tăng","increase","common"],
["giảm","decrease","common"],
["mở","open","common"],
["đóng","close","common"],
["đổ","pour","common"],
["trộn","mix","common"],
["khuấy","stir","common"],
["quan sát","observe","common"],
["nhận biết","identify","common"],
["phân biệt","distinguish","common"],
["cân bằng","balance","common"],
["tính","calculate","common"],
["chứa","contain","common"],
["gồm","consist of","common"],
["bao gồm","include","common"],
["bằng","equal to / by","common"],
["xảy ra","happen","common"],
["đo","measure","common"],
["nhận","receive","common"],
["mất","lose","common"],
["bị","be (passive)","common"],
["được","be / get / can","common"],
["mạnh","strong","common"],
["yếu","weak","common"],
["nặng","heavy","common"],
["nhẹ","light (weight)","common"],
["lớn","big / large","common"],
["nhỏ","small","common"],
["nhanh","fast","common"],
["chậm","slow","common"],
["nhiều","many / much","common"],
["ít","few / little","common"],
["đủ","enough","common"],
["dư","excess","common"],
["thiếu","lack","common"],
["mới","new","common"],
["cũ","old","common"],
["khác","different","common"],
["giống","same / similar","common"],
["đúng","correct / right","common"],
["sai","wrong / incorrect","common"],
["tốt","good","common"],
["xấu","bad","common"],
["hợp lý","reasonable","common"],
["bền vững","sustainable","common"],
["nhất","most","common"],
["hơn","more than","common"],
["rất","very","common"],
["chỉ","only","common"],
["có thể","can / may","common"],
["không thể","cannot","common"],
["luôn","always","common"],
["sau","after","common"],
["trước","before","common"],
["cuối","last / end","common"],
["đầu","first / head","common"],
["không","no / not","common"],
["có","have / there is","common"],
["là","is / to be","common"],
["của","of","common"],
["và","and","common"],
["hoặc","or","common"],
["với","with","common"],
["nếu","if","common"],
["khi","when","common"],
["vì","because","common"],
["do","due to","common"],
["nhưng","but","common"],
["tuy nhiên","however","common"],
["vì vậy","therefore","common"],
["để","in order to","common"],
["trong","in / inside","common"],
["ngoài","outside","common"],
["trên","on / above","common"],
["dưới","below / under","common"],
["giữa","between","common"],
["vào","into","common"],
["ra","out","common"],
["lên","up","common"],
["xuống","down","common"],
["sang","across / over","common"],
["theo","according to","common"],
["từ","from","common"],
["đến","to / arrive","common"],
["cho","to / for / give","common"],
["bởi","by","common"],
["sau đó","after that","common"],
["sau khi","after","common"],
["trước khi","before","common"],
["cùng","together","common"],
["mỗi","each / every","common"],
["mọi","every","common"],
["một","one / a","common"],
["hai","two","common"],
["ba","three","common"],
["bốn","four","common"],
["các","the / various","common"],
["này","this","common"],
["đó","that","common"],
["nào","which","common"],
["sau đây","below / following","common"],
["còn","still / and","common"],
["sẽ","will (future)","common"],
["đã","already (past)","common"],
["đang","be doing (progressive)","common"],
["lại","again","common"],
["nơi","place","common"],
["đâu","where","common"],
["thế","thus / so","common"],
["sao","why / how","common"],
["lửa","fire / flame","common"],
["dập tắt","extinguish","common"],
["hậu quả","consequence","common"],
["gây","cause","common"],
["tham gia","participate","common"],
["bảo vệ","protect","common"],
["phát triển","develop","common"],
["sản xuất","produce","common"],
["áp dụng","apply","common"],
["hoạt động","operate / activity","common"],
["chức năng","function","common"],
["phục hồi","recover","common"],
["nguyên nhân","cause / reason","common"],
["thí dụ","example","common"],
["thực hiện","carry out / perform","common"],
["khoẻ","healthy","common"],
["khoẻ mạnh","healthy","common"],
["bệnh","disease","common"],
["cơ thể","body","common"],
["con người","human","common"],
["trẻ em","child","common"],
["người","person","common"],
["học sinh","student","common"],
["thế giới","world","common"],
["mang","carry","common"],
["đặt","place","common"],
["lấy","take","common"],
["cho","give","common"]
,
/* ===== Bonus single-word terms to boost coverage ===== */
["tế bào","cell"],
["mô","tissue"],
["cơ quan","organ"],
["hệ cơ quan","organ system"],
["cơ thể","body"],
["cấu tạo","structure"],
["bộ phận","part / component"],
["chức năng","function"],
["vai trò","role"],
["quá trình","process"],
["chuyển động","movement / motion"],
["chuyển hóa","metabolism"],
["trao đổi chất","metabolism"],
["chủ động","voluntary / active"],
["chủ yếu","mainly"],
["chủ","main / master","common"],
["hoạt động","activity / operate","common"],
["cảm nhận","sense / feel","common"],
["cảm giác","sensation"],
["bài tiết","excrete / excretion"],
["nội tiết","endocrine"],
["ngoại tiết","exocrine"],
["tiết ra","secrete"],
["tiết","secrete / period","common"],
["tiết kiệm","save (resources)","common"],
["co cơ","muscle contraction"],
["co rút","contract"],
["vận động","movement","common"],
["sống","live / alive","common"],
["sinh","born / produce","common"],
["sinh học","biology"],
["sinh thái","ecology"],
["loài","species","common"],
["tự nhiên","natural / nature"],
["hệ","system","common"],
["lớp","layer / class","common"],
["lớp ngoài cùng","outermost layer"],
["lớp tế bào","cell layer"],
["mặt","face / surface","common"],
["mặt trời","Sun"],
["bề mặt","surface"],
["hình thức","form / way"],
["hình","shape / form","common"],
["tổng quát","general"],
["chính","main","common"],
["chính xác","accurate / precise"],
["tiếp xúc","contact"],
["tiếp","continue / contact","common"],
["liên tục","continuously"],
["thường xuyên","frequently","common"],
["định kỳ","periodic / regular"],
["mức độ","level / degree"],
["mức","level","common"],
["độ","degree","common"],
["tỉ lệ","ratio"],
["dạng","form / shape"],
["loại","type","common"],
/* ===== Physics: more electricity & general ===== */
["vật","object / thing","common"],
["vật lý","physics"],
["vật chất","matter"],
["vật thể","object"],
["vật cách nhiệt","thermal insulator"],
["vật dẫn nhiệt","thermal conductor"],
["điện","electricity","common"],
["điện năng","electrical energy"],
["điện áp","voltage"],
["mạch","circuit / vessel","common"],
["dòng","flow / stream"],
["dòng điện một chiều","direct current (DC)"],
["nguồn","source","common"],
["sáng","bright / light","common"],
["phát sáng","emit light"],
["đèn","lamp / light","common"],
["đèn pin","flashlight"],
["nóng","hot","common"],
["nóng lên","heat up"],
["lạnh","cold","common"],
["nhiệt","heat","common"],
["nhiệt lượng","heat (Q)"],
["truyền","transmit / transfer","common"],
["dẫn","conduct / lead","common"],
["dẫn nhiệt tốt","good thermal conductor"],
["năng","energy (in compounds)","common"],
["năng lượng","energy"],
["công","work / public","common"],
["công suất","power (P)"],
["hút","attract / suck","common"],
["đẩy","push / repel"],
["chiều","direction / dimension","common"],
["định","fix / establish","common"],
["định luật","law (scientific)"],
["định nghĩa","definition"],
/* ===== Anatomy & physiology more ===== */
["cơ","muscle","common"],
["xương sườn","rib"],
["khớp háng","hip joint"],
["thân","body / trunk","common"],
["chân","leg","common"],
["tay","hand / arm","common"],
["đầu","head","common"],
["thanh","bar / sound"],
["nuốt","swallow"],
["ăn","eat","common"],
["uống","drink","common"],
["thức ăn","food"],
["hệ vận động","musculoskeletal system"],
["chế độ","regimen / mode"],
["dinh dưỡng","nutrition"],
["chất dinh dưỡng","nutrient"],
["khẩu phần","dietary portion"],
["chất xơ","fiber"],
["vitamin C","vitamin C"],
["vitamin A","vitamin A"],
["vitamin D","vitamin D"],
["vitamin K","vitamin K"],
["vitamin B","vitamin B"],
["calcium","calcium (Ca)"],
["natri","sodium (Na)"],
["kali","potassium (K)"],
["sắt","iron (Fe)"],
/* ===== Anatomy systems more ===== */
["nhãn cầu","eyeball"],
["dây thần kinh thị giác","optic nerve"],
["màng nhĩ","eardrum"],
["xương con","ear ossicles"],
["hệ tim mạch","cardiovascular system"],
["nhịp tim","heart rate"],
["lối sống","lifestyle"],
["stress","stress"],
["ngủ","sleep","common"],
["giấc ngủ","sleep"],
["thể dục","exercise"],
["tập thể dục","do exercise"],
/* ===== Physics more ===== */
["mol","mole"],
["mật độ","density"],
["khối lượng riêng","density"],
["sét","lightning"],
["điện trở","resistance / resistor"],
["điện trở rất nhỏ","very small resistance"],
["điện trở rất lớn","very large resistance"],
["xoay chiều","alternating (AC)"],
["50 Hz","50 Hz (mains frequency)"],
["mạng điện","power grid"],
["mạng điện sinh hoạt","household mains"],
["thiết bị điện","electrical device"],
["thiết bị","device / equipment"],
["thiết bị tiêu thụ","load / consumer device"],
["tiêu thụ","consume / consumption"],
["tải","load (electrical)"],
["định mức","rated"],
["công suất tiêu thụ","power consumption"],
/* ===== Common verbs / connectors more ===== */
["ở","at / in / live","common"],
["nhau","each other","common"],
["động","move / motion","common"],
["thành","become / form","common"],
["làm","make / do","common"],
["quan","observe / important","common"],
["nên","should / so","common"],
["cả","both / all","common"],
["đều","all / equally","common"],
["tiêu","digest / consume","common"],
["chuyển","move / transfer","common"],
["co","contract","common"],
["cần","need","common"],
["ăn","eat","common"],
["khí","gas / breath","common"],
["áo","shirt / clothing","common"],
["điều","thing / regulate","common"],
["kim","needle / metal","common"],
["giúp","help","common"],
["phân","divide / fertilizer","common"],
["tế","cell (compound)","common"],
["bào","cell (compound)","common"],
["tác","act / effect","common"],
["thể","body / form","common"],
["phải","must / right","common"],
["đơn","simple / single","common"],
["giữ","keep / hold","common"],
["thức","food / awareness","common"],
["tử","atom / die","common"],
["toàn","complete / whole","common"],
["tự","self","common"],
["vị","taste / position","common"],
["đi","go","common"],
["hiện","appear / current","common"],
["chiều","direction","common"],
["điểm","point","common"],
["rõ","clear","common"],
["dài","long","common"],
["ngắn","short","common"],
["mềm","soft","common"],
["cứng","hard / rigid","common"],
["dẻo","flexible","common"],
["giòn","brittle","common"],
["khô","dry","common"],
["ướt","wet","common"],
["ẩm","damp / humid","common"],
["bẩn","dirty","common"],
["sạch","clean","common"],
["nguyên","whole / original","common"],
["thật","real / really","common"],
["xa","far","common"],
["gần","near","common"],
["khoảng","approximately / interval","common"],
["khoảng cách","distance"],
["hầu hết","most / mostly","common"],
["một số","some","common"],
["tất cả","all","common"],
["còn","still / and","common"],
["nữa","more / additionally","common"],
["vẫn","still","common"],
["cũng","also","common"],
["đặc biệt","especially","common"],
["đặc trưng","characteristic","common"],
["thông thường","commonly","common"],
["thông qua","through / via","common"],
["thông","through / common","common"],
["tự nhiên","natural","common"],
["nhân tạo","artificial","common"],
["bị","suffer / passive","common"],
["chống","resist / against","common"],
["bảo vệ","protect","common"],
["chống lại","fight against","common"],
["đặt","place","common"],
["mang","carry","common"],
["đem","bring","common"],
["lấy","take","common"],
["đeo","wear (glasses)","common"],
["tạt","splash","common"],
["bóp","squeeze","common"],
["nặn","press out","common"],
["trùm","cover over","common"],
["bay","fly","common"],
["chìm","sink","common"],
["nổi","float","common"],
["rơi","fall","common"],
["bốc","rise / evaporate","common"],
["thổi","blow","common"],
["ngắt","cut off / disconnect","common"],
["nối","connect","common"],
["đứt","broken / disconnected","common"],
["hỏng","broken / faulty","common"],
["chết","die","common"],
["sống","alive","common"],
["bệnh","disease","common"],
["khỏe","healthy","common"],
["khoẻ","healthy","common"],
["sức khoẻ","health","common"],
["nguy hiểm","dangerous","common"],
["gây nguy hiểm","cause danger","common"],
["nguyên nhân","cause / reason","common"],
["kết quả","result","common"],
["hậu quả","consequence","common"],
["lý do","reason","common"],
["chương trình","program / curriculum","common"],
["bài","lesson / problem","common"],
["bài học","lesson","common"],
["lớp 8","grade 8","common"],
["lớp học","classroom","common"],
["trường","school","common"],
["thầy","teacher","common"],
["cô","teacher / lady","common"],
["sách","book","common"],
["số lần","number of times","common"]

,
/* extra fillers */
["nước","water"],
["qua","through / past","common"],
["chất","substance","common"],
["lượng","amount","common"],
["hóa","transform","common"],
["dụng","use","common"],
["sự","fact / event","common"],
["hợp","combine","common"],
["học","study / learn","common"],
["tạo","form / create","common"],
["dùng","use","common"]

];
